name: study_ready
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.5
  flutter_svg: ^2.0.9
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5



  # local drift database dependencies

  drift: ^2.13.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.3

  #

  # json converter

  json_annotation: ^4.8.1

  #

  # analyzer for pab get work

  analyzer: ^6.2.0
  bloc: ^8.1.2

  #

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  # local drift database dependencies

  drift_dev: ^2.13.0
  build_runner: ^2.4.6

  #


flutter:
  uses-material-design: true
  assets:
    - assets/images/splash/logo.png
    - assets/images/splash/logo_for_android_12+.png
    - assets/icons/
    - assets/icons/home_screen/
    - assets/images/trainer/backgroung_for_trainer.svg
    - assets/images/trainer/picture_for_trainer.svg
    - assets/images/trainer/background_for_app_bar_trainer.svg
    - assets/jsons/trainers.json

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
