name: study_ready
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.19.5
  cloud_firestore: ^4.15.8
  flutter_svg: any
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.7
  analyzer: ^6.4.1
  loading_animation_widget: ^1.2.1
  flutter_native_splash: ^2.3.6
  drift: ^2.15.0
  sqlite3_flutter_libs: ^0.5.20
  path_provider: ^2.1.2
  path: ^1.9.0
  sqlite3: ^2.3.0
  hydrated_bloc: ^9.1.5
  json_annotation: ^4.8.1
  firebase_core:  ^2.31.0
  firebase_storage: ^11.6.10
  flutter_pdfview: ^1.3.2
  webview_flutter: ^4.7.0
  file_picker: ^6.2.0
  easy_autocomplete: ^1.6.0
  shared_preferences: ^2.2.2
  firebase_app_check: ^0.2.1+19
  fluttertoast: ^8.2.4
  rive: ^0.13.2
  
  



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  drift_dev: ^2.15.0


 

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icons/home_screen/
    - assets/icons/first_screen/
    - assets/icons/settings_screen/
    - assets/icons/registration_screen/
    - assets/images/trainer/background_for_trainer.svg
    - assets/images/trainer/background1_for_trainer.svg
    - assets/images/trainer/background2_for_trainer.svg
    - assets/images/trainer/background3_for_trainer.svg
    - assets/images/trainer/picture_for_trainer.svg
    - assets/images/trainer/background_for_app_bar_trainer.svg
    - assets/jsons/trainer1.json
    - assets/jsons/trainer2.json
    - assets/rive/duck_walk.riv
    - assets/rive/pencil_dude_hello.riv
    - assets/images/settings/settings_background.svg
    - assets/images/splash/logo1.png

  