// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzP3r-R1jxu_RFUKuDdv6IEsRDG149eJY',
    appId: '1:665255913349:web:58e97fcb3c37bb5df5c6ec',
    messagingSenderId: '665255913349',
    projectId: 'studyready-df819',
    authDomain: 'studyready-df819.firebaseapp.com',
    storageBucket: 'studyready-df819.appspot.com',
    measurementId: 'G-25GBZDD3DH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnsEv2mcXSQ5vWpOxJclb3or0xU8LOyxc',
    appId: '1:665255913349:android:79650fd165976a25f5c6ec',
    messagingSenderId: '665255913349',
    projectId: 'studyready-df819',
    storageBucket: 'studyready-df819.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy7akt5BOwwpm9IwJ8W63-gBZuF3J_6D4',
    appId: '1:665255913349:ios:586ea92f38c50c59f5c6ec',
    messagingSenderId: '665255913349',
    projectId: 'studyready-df819',
    storageBucket: 'studyready-df819.appspot.com',
    iosBundleId: 'com.example.studyReady',
  );
}
